import Table from "react-bootstrap/cjs/Table.js";
import React from "react";
function DataTable({ data }) {
    return (React.createElement(Table, { striped: true, bordered: true, hover: true },
        React.createElement("thead", null,
            React.createElement("tr", null,
                React.createElement("th", null, "Event Code"),
                React.createElement("th", null, "Event Name"),
                React.createElement("th", null, "Event Country"),
                React.createElement("th", null, "Tournament Code"),
                React.createElement("th", null, "Tournament Name"),
                React.createElement("th", null, "Gender"),
                React.createElement("th", null, "Tournament Country"),
                React.createElement("th", null, "Start Date Qualification"),
                React.createElement("th", null, "End Date Qualification"),
                React.createElement("th", null, "Start Date Main Draw"),
                React.createElement("th", null, "End Date Main Draw"),
                React.createElement("th", null, "Number in the Tournament"),
                React.createElement("th", null, "Local Date"),
                React.createElement("th", null, "Local Time"),
                React.createElement("th", null, "Team A federation Code"),
                React.createElement("th", null, "Team B federation Code"),
                React.createElement("th", null, "Team A Name"),
                React.createElement("th", null, "Team B Name"),
                React.createElement("th", null, "Court "),
                React.createElement("th", null, "Matchpoints Team A"),
                React.createElement("th", null, "Matchpoints Team B"),
                React.createElement("th", null, "Set 1 Points Team A"),
                React.createElement("th", null, "Set 2 Points Team A"),
                React.createElement("th", null, "Set 3 Points Team A"),
                React.createElement("th", null, "Set 1 Points Team B"),
                React.createElement("th", null, "Set 2 Points Team B"),
                React.createElement("th", null, "Set 3 Points Team B"),
                React.createElement("th", null, "Duration Set 1"),
                React.createElement("th", null, "Duration Set 2"),
                React.createElement("th", null, "Duration Set 3"))),
        React.createElement("tbody", null, data.map((row, index) => (
        // biome-ignore lint/suspicious/noArrayIndexKey: <explanation>
        React.createElement("tr", { key: index },
            React.createElement("td", null, row.Event_Code),
            React.createElement("td", null, row.event_name),
            React.createElement("td", null, row.event_country),
            React.createElement("td", null, row.tournament_code),
            React.createElement("td", null, row.tournament_name),
            React.createElement("td", null, row.gender),
            React.createElement("td", null, row.countrycode),
            React.createElement("td", null, row.startdatequalification),
            React.createElement("td", null, row.enddatequalification),
            React.createElement("td", null, row.startdatemaindraw),
            React.createElement("td", null, row.enddatemaindraw),
            React.createElement("td", null, row.numberinthetournament),
            React.createElement("td", null, row.localdate.toString()),
            React.createElement("td", null, row.lokaltime.toString()),
            React.createElement("td", null, row.teamafederationcode),
            React.createElement("td", null, row.teambfederationcode),
            React.createElement("td", null, row.teamaname),
            React.createElement("td", null, row.teambname),
            React.createElement("td", null, row.court),
            React.createElement("td", null, row.matchpointsteamA),
            React.createElement("td", null, row.matchpointsteamB),
            React.createElement("td", null, row.pointsteamaset1),
            React.createElement("td", null, row.pointsteamaset2),
            React.createElement("td", null, row.pointsteamaset3),
            React.createElement("td", null, row.pointsteambset1),
            React.createElement("td", null, row.pointsteambset2),
            React.createElement("td", null, row.pointsteambset3),
            React.createElement("td", null, row.durationset1),
            React.createElement("td", null, row.durationset2),
            React.createElement("td", null, row.durationset3)))))));
}
export default DataTable;
