version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BeachVolleyBall
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - BeachMesh
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BeachVolleyBall
    networks:
      - BeachMesh
volumes:
  db_data:
networks:
  BeachMesh:


